# openapi2-run.yaml
swagger: '2.0'
info:
  title: Composite Service API
  description: Sample API on API Gateway with a Cloud Run backend
  version: 1.0.0
schemes:
- https
produces:
- application/json
x-google-backend:
  address: https://main-feed-service-745799261495.us-east4.run.app
securityDefinitions:
  api-gw:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "api-gw@w4153-cloud-computing.iam.gserviceaccount.com"
    x-google-jwks_uri: "https://www.googleapis.com/robot/v1/metadata/x509/api-gw@w4153-cloud-computing.iam.gserviceaccount.com"
    x-google-audiences: "https://w4153-test"
security:
  - api-gw: []
paths:
  /:
    get:
      summary: hello world
      operationId: hello
      responses:
        '200':
          description: A successful response
  /main_feed:
    get:
      summary: Get main feed for user posts and comments
      operationId: getMainFeed
      responses:
        '200':
          description: A successful response
